# Generated by Django 5.2.7 on 2025-10-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolver_ip', models.GenericIPAddressField()),
                ('qname', models.CharField(max_length=255)),
                ('qtype', models.CharField(max_length=10)),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('geo', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
